name: smart_kitchen
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Bloc
  flutter_bloc: ^7.2.0
  equatable: ^2.0.0

  # International
  intl: ^0.17.0

  # Firebase
  cloud_firestore: ^2.5.1
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0

  # Flushbar
  another_flushbar: ^1.10.24

  # Shared preferences
  shared_preferences: ^2.0.7

  # Database
  hive: ^2.0.4
  hive_generator: ^1.1.0
  hive_flutter: ^1.1.0

  # Ads
  #google_mobile_ads: ^0.13.0

  # Icons and fonts
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0

  # Speech to text
  speech_to_text: ^4.2.1

  # UUID
  uuid: ^3.0.4

  # Connection
  connectivity: ^3.0.3

  # Authentication
  google_sign_in: ^5.0.7
  flutter_signin_button: ^2.0.0

  # Shake
  shake: ^1.0.1

  # Intro slider
  intro_slider: ^3.0.2

  # Path provider
  path_provider: ^2.0.2

  # String similarity
  string_similarity: ^2.0.0

  # Rating
  flutter_rating_bar: ^4.0.0

  # Switch
  toggle_switch: ^1.2.0

  # Pickers
  numberpicker: ^2.1.1
  image_picker: ^0.8.4+1

  # Logger
  logger: ^1.1.0

  # Calendar
  calendar_appbar: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  freezed: ^0.14.2
  build_runner:
  json_serializable: ^4.0.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/noimage.jpg
    - assets/cookpanel.jpg
    - assets/cookpanelwhite.jpg
    - assets/recipe/
